- hosts: localhost
  gather_facts: no
  tasks:
  - set_fact:
      collectd_conf_output_dir: "/tmp/collectd.conf.d"
  - import_role:
      name: "collectd_config"
  - import_role:
      name: "collectd"
